collapsed: false
sidebar:
  - categories: Categories
  - files: Files
  - definition: Definition
  - skill: Skill
  - connection: Connection
  - expression: Expression
  - appearance: Appearance
  - rewards: Rewards
  - calculations: Calculations
  - experience-sources: Experience Sources
  - migrations: Migrations