collapsed: false
sidebar:
  - files: Files
  - expressions: Expressions
  - frames: Frames
  - icons: Icons
  - background: Background
  - colors: Colors
  - text: Text
  - categories: Categories
  - definitions: Definitions
  - skills: Skills
  - connections: Connections
  - roots: Roots
  - rewards: Rewards
  - calculations: Calculations
  - experience-sources: Experience Sources
  - migrations: Migrations